# Generated by Django 4.1.2 on 2022-10-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkalias',
            name='alias',
            field=models.CharField(max_length=32, unique=True, verbose_name='Псевдоним'),
        ),
    ]
