# Generated by Django 4.1 on 2022-08-26 19:06
from django.contrib.postgres.operations import CITextExtension

import apps.accounts.managers
import apps.accounts.validators
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CITextExtension(),
    ]
